// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotasDisciplinarias.API.Data;

#nullable disable

namespace NotasDisciplinarias.API.Migrations
{
    [DbContext(typeof(NotasDbContext))]
    partial class NotasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Accion", b =>
                {
                    b.Property<int>("id_accion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_accion"));

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_cumpl")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_accion");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Casos", b =>
                {
                    b.Property<int>("IdCaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_caso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaso"));

                    b.Property<int?>("CategoriaId_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("UsuarioId_Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdCaso");

                    b.HasIndex("CategoriaId_Categoria");

                    b.HasIndex("UsuarioId_Usuario");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Documento", b =>
                {
                    b.Property<int>("id_documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_documento"));

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("ruta_formato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ruta_guardado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_documento");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Evidencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaso");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.PanelAdmin", b =>
                {
                    b.Property<int>("id_panel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_panel"));

                    b.Property<int>("acciones_realizadas")
                        .HasColumnType("int");

                    b.Property<int>("documentos_generados")
                        .HasColumnType("int");

                    b.Property<int>("evidencias_subidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_revision")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_panel");

                    b.ToTable("PanelAdmin");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Paso", b =>
                {
                    b.Property<int>("id_paso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_paso"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("nombre_paso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_paso");

                    b.ToTable("Pasos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.SeguimientoProceso", b =>
                {
                    b.Property<int>("id_seguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seguimiento"));

                    b.Property<string>("estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_paso")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_seguimiento");

                    b.ToTable("SeguimientoProcesos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Area");

                    b.Property<int?>("Id_Jefe_Inmediato")
                        .HasColumnType("int")
                        .HasColumnName("id_jefe_inmediato");

                    b.Property<string>("Nombre_Completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rol");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Casos", b =>
                {
                    b.HasOne("NotasDisciplinarias.API.Models.Categoria", null)
                        .WithMany("Casos")
                        .HasForeignKey("CategoriaId_Categoria");

                    b.HasOne("NotasDisciplinarias.API.Models.Usuario", null)
                        .WithMany("Casos")
                        .HasForeignKey("UsuarioId_Usuario");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Evidencias", b =>
                {
                    b.HasOne("NotasDisciplinarias.API.Models.Casos", "Caso")
                        .WithMany()
                        .HasForeignKey("IdCaso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caso");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Categoria", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Usuario", b =>
                {
                    b.Navigation("Casos");
                });
#pragma warning restore 612, 618
        }
    }
}
