// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotasDisciplinarias.API.Data;

#nullable disable

namespace NotasDisciplinarias.API.Migrations
{
    [DbContext(typeof(NotasDbContext))]
    partial class NotasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Accion", b =>
                {
                    b.Property<int>("id_accion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_accion"));

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_cumpl")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_accion");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Caso", b =>
                {
                    b.Property<int>("id_caso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_caso"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id_caso");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Documento", b =>
                {
                    b.Property<int>("id_documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_documento"));

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("ruta_formato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ruta_guardado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_documento");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Casoid_caso")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_subida")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("tipo_archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Casoid_caso");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.PanelAdmin", b =>
                {
                    b.Property<int>("id_panel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_panel"));

                    b.Property<int>("acciones_realizadas")
                        .HasColumnType("int");

                    b.Property<int>("documentos_generados")
                        .HasColumnType("int");

                    b.Property<int>("evidencias_subidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_revision")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_panel");

                    b.ToTable("PanelAdmin");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Paso", b =>
                {
                    b.Property<int>("id_paso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_paso"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caso")
                        .HasColumnType("int");

                    b.Property<string>("nombre_paso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_paso");

                    b.ToTable("Pasos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.SeguimientoProceso", b =>
                {
                    b.Property<int>("id_seguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seguimiento"));

                    b.Property<string>("estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_paso")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_seguimiento");

                    b.ToTable("SeguimientoProcesos");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jefe_inmediato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NotasDisciplinarias.API.Models.Evidencia", b =>
                {
                    b.HasOne("NotasDisciplinarias.API.Models.Caso", "Caso")
                        .WithMany()
                        .HasForeignKey("Casoid_caso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caso");
                });
#pragma warning restore 612, 618
        }
    }
}
